TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
# Create and install (or just install)
# databases, templates, substitutions like this

#DB += my_file.template
DB += ioc_vsam0.template
DB += ioc_vsam0name.template
DB += vsam
DB += vsam.db
DB += vsam.template
DB += vsam_ch
DB += vsam_ch.db
DB += vsam_chname.db
DB += vsam_ctrlname.db
DB += vsam_global
DB += vsam_global.db
DB += vsam_module
DB += vsam_module.db

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

