TOP=../../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#INSTALL_HTML = $(WWW_DIR)/site/vsam
HTMLS += vsam_index.html
HTMLS += VSAM-HOW-TO
HTMLS += VSAM_ioc_mods
HTMLS += vsam.gif
HTMLS += vsam_data.gif
HTMLS += vsam_details.gif
HTMLS += vsam_module.gif
HTMLS += vsam.doc
HTMLS += vsam_busError.txt
HTMLS += vsam_bugs.html
HTMLS += vsam_releaseNotes.html

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

